--------------------------------------------------------
-- Archivo creado  - viernes-septiembre-23-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PJ_AREA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_AREA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"ID_CIUDAD" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_ASIGNACION_X_BIENES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_ASIGNACION_X_BIENES" 
   (	"ID" NUMBER, 
	"ID_BIEN" NUMBER, 
	"ID_ASINACION" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_ASINACION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_ASINACION" 
   (	"ID" NUMBER, 
	"FECHA_ASIGNACION" NUMBER, 
	"OBSERVACION" VARCHAR2(20 BYTE), 
	"ID_AREA" NUMBER, 
	"ID_PERSONA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_BIENES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_BIENES" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"SERIAL" VARCHAR2(20 BYTE), 
	"NUM_INVE" VARCHAR2(20 BYTE), 
	"PESO" VARCHAR2(20 BYTE), 
	"ALTO" VARCHAR2(20 BYTE), 
	"ANCHO" VARCHAR2(20 BYTE), 
	"LARGO" VARCHAR2(20 BYTE), 
	"VALOR_COMPRA" VARCHAR2(20 BYTE), 
	"FECHA_COMPRA" DATE, 
	"ID_TIPO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_CIUDAD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_CIUDAD" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_PERSONA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_PERSONA" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"IDENTIFICACION" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ID_AREA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_TIPO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_TIPO" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PJ_USUARIO
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."PJ_USUARIO" 
   (	"ID" NUMBER, 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASENA" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"ESTADO" VARCHAR2(20 BYTE), 
	"ID_PERSONA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_AREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_AREA_PK" ON "SYSTEM"."PJ_AREA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_ASINACION_X_BIENES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_ASINACION_X_BIENES_PK" ON "SYSTEM"."PJ_ASIGNACION_X_BIENES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_ASINACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_ASINACION_PK" ON "SYSTEM"."PJ_ASINACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_BIENES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_BIENES_PK" ON "SYSTEM"."PJ_BIENES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_CIUDAD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_CIUDAD_PK" ON "SYSTEM"."PJ_CIUDAD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_PERSONA_PK" ON "SYSTEM"."PJ_PERSONA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_TIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_TIPO_PK" ON "SYSTEM"."PJ_TIPO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PJ_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PJ_USUARIO_PK" ON "SYSTEM"."PJ_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UQ_PERSONA
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UQ_PERSONA" ON "SYSTEM"."PJ_USUARIO" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger PJ_AREA_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_AREA_TRG" 
BEFORE INSERT ON PJ_AREA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_AREA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_AREA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_ASINACION_X_BIENES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_ASINACION_X_BIENES_TRG" 
BEFORE INSERT ON "PJ_ASIGNACION_X_BIENES" 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_ASINACION_X_BIENES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_ASINACION_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_ASINACION_TRG" 
BEFORE INSERT ON PJ_ASINACION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_ASINACION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_BIENES_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_BIENES_TRG" 
BEFORE INSERT ON PJ_BIENES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_BIENES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_BIENES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_CIUDAD_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_CIUDAD_TRG" 
BEFORE INSERT ON PJ_CIUDAD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_CIUDAD_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_CIUDAD_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_PERSONA_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_PERSONA_TRG" 
BEFORE INSERT ON PJ_PERSONA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_PERSONA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_PERSONA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_TIPO_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_TIPO_TRG" 
BEFORE INSERT ON PJ_TIPO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_TIPO_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_TIPO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PJ_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."PJ_USUARIO_TRG" 
BEFORE INSERT ON PJ_USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PJ_USUARIO_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SYSTEM"."PJ_USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_AREA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_AREA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_AREA" ADD CONSTRAINT "PJ_AREA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_ASIGNACION_X_BIENES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_ASIGNACION_X_BIENES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_ASIGNACION_X_BIENES" ADD CONSTRAINT "PJ_ASINACION_X_BIENES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_ASINACION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_ASINACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_ASINACION" ADD CONSTRAINT "PJ_ASINACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_BIENES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_BIENES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_BIENES" ADD CONSTRAINT "PJ_BIENES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_CIUDAD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_CIUDAD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_CIUDAD" ADD CONSTRAINT "PJ_CIUDAD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_PERSONA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_PERSONA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_PERSONA" ADD CONSTRAINT "PJ_PERSONA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_TIPO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_TIPO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_TIPO" ADD CONSTRAINT "PJ_TIPO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PJ_USUARIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_USUARIO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."PJ_USUARIO" ADD CONSTRAINT "PJ_USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."PJ_USUARIO" ADD CONSTRAINT "UQ_PERSONA" UNIQUE ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_AREA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_AREA" ADD CONSTRAINT "FK_AREA_CIUDAD" FOREIGN KEY ("ID_CIUDAD")
	  REFERENCES "SYSTEM"."PJ_CIUDAD" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_ASIGNACION_X_BIENES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_ASIGNACION_X_BIENES" ADD CONSTRAINT "FK_ASIGNACION_BIEN" FOREIGN KEY ("ID_BIEN")
	  REFERENCES "SYSTEM"."PJ_BIENES" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."PJ_ASIGNACION_X_BIENES" ADD CONSTRAINT "FK_ASIGNACION_ASINACION" FOREIGN KEY ("ID_ASINACION")
	  REFERENCES "SYSTEM"."PJ_ASINACION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_ASINACION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_ASINACION" ADD CONSTRAINT "FK_ASINACION_PERSONA" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "SYSTEM"."PJ_PERSONA" ("ID") ENABLE;
  ALTER TABLE "SYSTEM"."PJ_ASINACION" ADD CONSTRAINT "FK_ASINACION_AREA" FOREIGN KEY ("ID_AREA")
	  REFERENCES "SYSTEM"."PJ_AREA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_BIENES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_BIENES" ADD CONSTRAINT "FK_BIENES_TIPO" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "SYSTEM"."PJ_TIPO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_PERSONA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_PERSONA" ADD CONSTRAINT "FK_PERSONA_AREA" FOREIGN KEY ("ID_AREA")
	  REFERENCES "SYSTEM"."PJ_AREA" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PJ_USUARIO
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."PJ_USUARIO" ADD CONSTRAINT "FK_USUARIO_PERSONA" FOREIGN KEY ("ID_PERSONA")
	  REFERENCES "SYSTEM"."PJ_PERSONA" ("ID") ENABLE;
